name: honest_dating
description: "A private Flutter skeleton for Honest Dating."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  firebase_core: '>=4.15.0 <4.16.0'
  firebase_auth: '>=6.7.0 <6.8.0'
  firebase_app_check: '>=0.4.8 <0.4.9'
  cloud_firestore: '>=6.10.0 <6.11.0'
  firebase_storage: ^13.6.0
  google_sign_in: ^7.2.0
  http: ^1.6.0
  image_picker: 1.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/resources/config/
    - lib/resources/localization/
    - lib/resources/images/discover/
